GROUP_ID ?= com.shutterfly.services
ARTIFACT_ID ?= test-service-example
VERSION ?= 1.0.0-SNAPSHOT
ENV ?= dev

USE_CORRETTO = true
JAVA_VERSION = 11

MAKE_COMMON ?= /etc/shutterfly/build/common/makerules

include $(MAKE_COMMON)/docker-springboard.mk
