APPLICATION_NAME=test-service-example

AWS_REGION=us-east-1

AWS_TIER=app

AWS_VPC_PREFIX = sfly-legacy

MAKE_COMMON ?= /etc/shutterfly/build/common/makerules

include $(MAKE_COMMON)/ecs-docker-deploy.mk
